version: '3'

tasks:
  dev:
    cmds:
      - air
  build:
    cmds:
      - templ generate
      - go build -o server cmd/main.go
  install:
    cmds:
      - go install github.com/a-h/templ/cmd/templ@latest
      - go install github.com/swaggo/swag/cmd/swag@latest
      - go install github.com/cosmtrek/air@latest
